/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
/**
 *
 * @author andres
 */
public class CuentaRevoluciones extends javax.swing.JPanel {
    private double revs;
    //private static int instances=0;

    /*
    public CuentaRevoluciones(){
        revs=0;
    }
    */

    public double getRevs(){
        return revs;
    }

    public void setRevs(double nuevo){
        revs=nuevo;
    }
    
    
    /**
     * Creates new form CuentaRevoluciones2
     */
    static int valor=0;
    
    public CuentaRevoluciones() {
        //instances++;
        revs=0;
        initComponents();
     /*       
            //ESTE CODIGO FUNCIONA, SACADO DE LA DOCUMENTACION OFICIAL
  ActionListener taskPerformer2 = new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
          jLabel1.setText(""+getRevs());
      }
  };
  new Timer(Mandos.delay, taskPerformer2).start();   
        */
    }
    
    public void actualizarCuentaRevoluciones(){
        jLabel1.setText(""+getRevs());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Cuentarrevoluciones"));

        jLabel1.setText(jLabel1.getText());
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder("RPM"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
