/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author andres
 */
public class CuentaKilometros extends javax.swing.JPanel {
    private double distancia;
    private double distanciaAbs;
 
     public double getDistancia(){
         return distancia;
     }
     
     public double getDistanciaAbs(){
         return distanciaAbs;
     }    
     
     private void resetDistancia(){
         distancia=0;
     }
 
     public void addDistancia(double velocidadActual){
         double res=velocidadActual*(Mandos.DELAY/3600000.0);    //Obtenido de la formula de la velocidad y despejando la distancia
         distancia+=res;
         distanciaAbs+=res;
     }
     
     /**
      * Creates new form CuentaKilometros
      */
     public CuentaKilometros() {
         distancia=0;
         distanciaAbs=0;
         
         initComponents();
     }
     
     public void actualizarCuentaKilometros(){
         contadorReciente.setText(String.format("%.2f", getDistancia()));
         contadorTotal.setText(String.format("%.2f", getDistanciaAbs()));      
     }
 
     /**
      * This method is called from within the constructor to initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is always
      * regenerated by the Form Editor.
      */
    
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {
 
         contadorReciente = new javax.swing.JLabel();
         contadorTotal = new javax.swing.JLabel();
         botonReset = new javax.swing.JButton();
 
         setBorder(javax.swing.BorderFactory.createTitledBorder("CuentaKilometros"));
 
         contadorReciente.setText("jLabel1");
         contadorReciente.setBorder(javax.swing.BorderFactory.createTitledBorder("Contador reciente"));
 
         contadorTotal.setText("jLabel2");
         contadorTotal.setBorder(javax.swing.BorderFactory.createTitledBorder("Contador total"));
 
         botonReset.setText("Reset");
         botonReset.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 botonResetActionPerformed(evt);
             }
         });
 
         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
         this.setLayout(layout);
         layout.setHorizontalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addComponent(contadorTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
             .addComponent(contadorReciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
             .addGroup(layout.createSequentialGroup()
                 .addGap(56, 56, 56)
                 .addComponent(botonReset)
                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         );
         layout.setVerticalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addComponent(contadorReciente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                 .addComponent(contadorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addGap(18, 18, 18)
                 .addComponent(botonReset)
                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         );
     }// </editor-fold>//GEN-END:initComponents
 
     //Boton reset del cuentakilometros para poner a 0 la distancia cuando se pulse
     private void botonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResetActionPerformed
         // TODO add your handling code here:
         resetDistancia();
     }//GEN-LAST:event_botonResetActionPerformed
 
 
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton botonReset;
     private javax.swing.JLabel contadorReciente;
     private javax.swing.JLabel contadorTotal;
     // End of variables declaration//GEN-END:variables
 }
 