
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.TimerTask;
import javax.swing.JToggleButton;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author andres
 */
public class Mandos extends javax.swing.JFrame {
    //private static Timer timer=new Timer(1000, null);//ap, en, ac, fr;
    private ActionListener apagar, encender, frenar, acelerar;
    
    public static int instances=0;
    Cliente c=new Cliente();
    /**
     * Creates new form Mandos
     */
    public Mandos() {
        /*
 apagar = new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
          c.peticion(EstadoMotor.APAGADO);
          //System.out.println("instances mando: "+instances);
      }      
  };             
  encender = new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
          c.peticion(EstadoMotor.ENCENDIDO);
          //System.out.println("instances mando: "+instances);
      }      
  };        
  
 acelerar = new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
          c.peticion(EstadoMotor.ACELERANDO);
          //System.out.println("instances mando: "+instances);
      }      
  };          
 
  frenar = new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
          c.peticion(EstadoMotor.FRENANDO);
          //System.out.println("instances mando: "+instances);
      }      
  };      
        */
//        timer=new Timer()
        instances++;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        salpicadero1 = c.getGestorFiltros().getCadenaFiltros().getSalpicadero();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("APAGADO");

        jToggleButton1.setForeground(new java.awt.Color(0, 255, 0));
        jToggleButton1.setText("ENCENDER");
        jToggleButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        jToggleButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Prueba(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed1(evt);
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("ACELERAR");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformedAcelerar(evt);
            }
        });

        jToggleButton3.setText("FRENAR");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformedFreno(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jToggleButton1)
                        .addGap(29, 29, 29)
                        .addComponent(jToggleButton2)
                        .addGap(28, 28, 28)
                        .addComponent(jToggleButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(salpicadero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton3))
                .addGap(35, 35, 35)
                .addComponent(salpicadero1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton3ActionPerformedFreno(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformedFreno
        //Solamente se entra si no esta el acelerador activado
        if(!jToggleButton2.isSelected()){

            //Primer caso: Encendido y pulsado
            if(jToggleButton3.isSelected() && jToggleButton1.isSelected()){
                jToggleButton3.setText("Soltar Freno");
                jToggleButton3.setForeground(Color.red);
                jLabel1.setText("FRENANDO");
                c.peticion(EstadoMotor.FRENANDO);
            }

            //Segundo caso: Soltado Freno
            else if(jToggleButton1.isSelected() && !jToggleButton3.isSelected()){
                jToggleButton3.setText("FRENAR");
                jToggleButton3.setForeground(Color.black);
                jLabel1.setText("ENCENDIDO");
                c.peticion(EstadoMotor.ENCENDIDO);
            }
            //Tercer caso: pulsado acelerador con el coche encendido

            //Tercer caso: Pulsado acelerador con el coche apagado
            else{
                //jToggleButton3.setSelected(false);
                resetFreno(jToggleButton3);
                c.peticion(EstadoMotor.APAGADO);
            }
        }
        else{
            //jToggleButton3.setSelected(false);
            resetFreno(jToggleButton3);
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformedFreno

    private void jToggleButton2ActionPerformedAcelerar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformedAcelerar
        //Solamente se entra si no esta el freno activado
        if(!jToggleButton3.isSelected()){
            //Primer caso: Encendido y pulsado
            if(jToggleButton2.isSelected() && jToggleButton1.isSelected()){
                jToggleButton2.setText("Soltar Acelerador");
                jToggleButton2.setForeground(Color.red);
                jLabel1.setText("ACELERANDO");
                c.peticion(EstadoMotor.ACELERANDO);
            }

            //Segundo caso: Soltado Acelerador
            else if(jToggleButton1.isSelected()){
                jToggleButton2.setText("ACELERAR");
                jToggleButton2.setForeground(Color.black);
                jLabel1.setText("ENCENDIDO");
                c.peticion(EstadoMotor.ENCENDIDO);
            }
            //Tercer caso: pulsado freno con el coche encendido
            //        else if(jToggleButton1.isSelected() && jToggleButton3.isSelected()){

                //      }

            //Tercer caso: Pulsado acelerador con el coche apagado
            else{
                //jToggleButton2.setSelected(false);
                resetAcelerador(jToggleButton2);
                
                c.peticion(EstadoMotor.APAGADO);
            }
        }
        else{
            //jToggleButton2.setSelected(false);
            resetAcelerador(jToggleButton2);
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformedAcelerar

    private void jToggleButton1ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed1
        if(jToggleButton1.isSelected()){
            jLabel1.setText("ENCENDIDO");
            jToggleButton1.setForeground(Color.red);
            jToggleButton1.setText("APAGAR");
            c.peticion(EstadoMotor.ENCENDIDO);

            resetAcelerador(jToggleButton2);
            resetFreno(jToggleButton3);
        }
        else{
            jLabel1.setText("APAGADO");
            jToggleButton1.setForeground(Color.green);
            jToggleButton1.setText("ENCENDER");
            
            
            /**
             * OBTENER LA FORMA DE CONSEGUIR QUE SE PUEDA DIRECCIONAR UN TIMER, EN CUYO CASO YA ESTARIA HECHO PORQUE EL PROBLEMA ES QUE ES NECESARIO PARAR TODOS LOS TIMERS
             */

            c.peticion(EstadoMotor.APAGADO);
            //if(c.getGestorFiltros().getCadenaFiltros().getSalpicadero().getEstado()==EstadoMotor.APAGADO)
            //System.out.println("APAGADO uwu");

            //jToggleButton2.setSelected(false);
            //jToggleButton3.setSelected(false);
            resetAcelerador(jToggleButton2);
            resetFreno(jToggleButton3);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed1

    
    void procesarPeticion(EstadoMotor estado){
  ActionListener res = new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
          c.peticion(estado);
          System.out.println("instances mando: "+instances);
      }
      
  };        
    }
    
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void Prueba(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Prueba
        // TODO add your handling code here:
        //jToggleButton1.setText("Esto es una prueba");
    }//GEN-LAST:event_Prueba

    private void jToggleButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jToggleButton1ItemStateChanged
        // TODO add your handling code here:
        //jToggleButton1.setText("Esto es una prueba");
    }//GEN-LAST:event_jToggleButton1ItemStateChanged

    //METODO INTERESANTE setSelected(boolean)
    private void resetFreno(JToggleButton freno){
        jToggleButton3.setText("FRENAR");
        jToggleButton3.setForeground(Color.black);
        //jLabel1.setText("ENCENDIDO");  
        jToggleButton3.setSelected(false);
    }
    
    
    private void resetAcelerador(JToggleButton acelerador){
        jToggleButton2.setText("ACELERAR");
        jToggleButton2.setForeground(Color.black);
        //jLabel1.setText("ENCENDIDO");  
        jToggleButton2.setSelected(false);        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mandos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mandos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mandos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mandos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mandos().setVisible(true);
                System.out.println("Esto es una prueba");
            }
        });
        /*
        TimerTask task=new TimerTask(){
            public void run(){
                System.out.println("Esto es otra prueba");
            }
        };
          */      
        /*
         Timer timer=new Timer("Timer");
         timer.schedule(task, 1, 1);
         timer.cancel();
*/
        

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private Salpicadero salpicadero1;
    // End of variables declaration//GEN-END:variables
}
