/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author andres
 */
public class Salpicadero extends javax.swing.JPanel {
    //Los demas metodos los pone NetBeans abajo
    final private double RADIO;	//Se pone de instancia por si se quiere crear otra con otros parametros

    public Salpicadero(){
        //En initComponents se inicializa el CuentaRrevoluciones,
        //CuentaKilometros y Velocimetro, esto es debido a que 
        //NetBeans lo realiza asi obligatoriamente cuando se tratan de JPanels
        initComponents();
        RADIO=0.15;
    }


    public void actualizarInfo(){
        velocidad.actualizarVelocimetro();
        distancia.actualizarCuentaKilometros();
        revs.actualizarCuentaRevoluciones();
    }

    public Salpicadero(double rads){
        initComponents();
        RADIO=(rads>0)?rads:0.1;
    }

    public double ejecutar(double revoluciones, EstadoMotor estado) {
        revs.setRevs(revoluciones);

        velocidad.calcularVelocidad(RADIO, revs.getRevs());	//MEJORABLE

        distancia.addDistancia(velocidad.getVelocidad());

        return  revs.getRevs();
    }


    //Seguramente esto este mal, hay que comprobarlo
    public double getRevs(){
        return revs.getRevs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        distancia = new CuentaKilometros();
        velocidad = new Velocimetro();
        revs = new CuentaRrevoluciones();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Salpicadero"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(revs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(revs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CuentaKilometros distancia;
    private CuentaRrevoluciones revs;
    private Velocimetro velocidad;
    // End of variables declaration//GEN-END:variables
}
