package Vista;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author andres
 */
public class Velocimetro extends javax.swing.JPanel {
    private Salpicadero salpicadero;

    public Velocimetro(Salpicadero s) {
        salpicadero=s;
        initComponents();
    }


    public void actualizarVelocimetro(){
        velDisplay.setText(String.format("%.2f", salpicadero.getObjetivo().getVelocidad()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        velDisplay = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Velocimetro"));
        setName("ejemplo"); // NOI18N

        velDisplay.setText(""+salpicadero.getObjetivo().getVelocidad());
        velDisplay.setBorder(javax.swing.BorderFactory.createTitledBorder("Km/h"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(velDisplay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(velDisplay, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel velDisplay;
    // End of variables declaration//GEN-END:variables
}
