package Vista;

import java.awt.Color;
import javax.swing.JPanel;

import Modelo.EstadoMotor;

public class Combustible extends JPanel{
    private Salpicadero s;
    /**
     * Creates new form Combustible
     */
    public Combustible(Salpicadero s) {
        this.s=s;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        radial1Vertical1 = new eu.hansolo.steelseries.gauges.Radial1Vertical();
        jButton1 = new javax.swing.JButton();
        radial1Square1 = new eu.hansolo.steelseries.gauges.Radial1Square();

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 48)); // NOI18N
        jLabel1.setText("Combustible bajo");
        jLabel1.setForeground(Color.red);
        jLabel1.setVisible(false);

        radial1Vertical1.setTitle("Fuel");
        radial1Vertical1.setUnitString("%");

        jButton1.setText("REPOSTAJE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        radial1Square1.setMaxValue(15.0);
        radial1Square1.setTitle("Consumo");
        radial1Square1.setUnitString("L/100Km");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(radial1Square1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(radial1Vertical1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jButton1)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radial1Square1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radial1Vertical1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(s.getObjetivo().getEstado() == EstadoMotor.APAGADO)
            s.getObjetivo().llenarCombustible();
    }                                        

    public void revisarGasolina(){
        if(s.getObjetivo().getCombustible() < s.getObjetivo().getCombustibleMax()*s.getObjetivo().getCombustibleAviso()){
            jLabel1.setVisible(true);
        }
        else
            jLabel1.setVisible(false);
    }

    public void updateGauges(){
        //System.out.println("CONSUMO: "+s.getObjetivo().getConsumo());
        radial1Square1.setValue(100*s.getObjetivo().getConsumo());
        radial1Vertical1.setValue((s.getObjetivo().getCombustible()/s.getObjetivo().getCombustibleMax())*100);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private eu.hansolo.steelseries.gauges.Radial1Square radial1Square1;         //Consumo
    private eu.hansolo.steelseries.gauges.Radial1Vertical radial1Vertical1;     //Gasolina
    // End of variables declaration         
}