package Vista;
import Modelo.EstadoMotor;

import java.awt.Color;

import javax.swing.JPanel;

public class Revision extends JPanel{
    Salpicadero s;
    /**
     * Creates new form Revision
     */
    public Revision(Salpicadero s) {
        this.s=s;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pastillasLabel = new javax.swing.JLabel();
        aceiteLabel = new javax.swing.JLabel();
        revisionLabel = new javax.swing.JLabel();
        rotPastillaLabel = new javax.swing.JLabel();
        rotAceiteLabel = new javax.swing.JLabel();
        rotRevisionLabel = new javax.swing.JLabel();
        pastillasReset = new javax.swing.JButton();
        aceiteReset = new javax.swing.JButton();
        revisionReset = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Panel de revisión"));

        pastillasLabel.setText("Pastillas");

        aceiteLabel.setText("Aceite");

        revisionLabel.setText("Revisión");

        rotPastillaLabel.setText("jLabel1");

        rotAceiteLabel.setText("jLabel5");

        rotRevisionLabel.setText("jLabel6");

        pastillasReset.setText("Reset");
        pastillasReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastillasResetActionPerformed(evt);
            }
        });

        aceiteReset.setText("Reset");
        aceiteReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceiteResetActionPerformed(evt);
            }
        });

        revisionReset.setText("Reset");
        revisionReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revisionResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pastillasReset))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rotPastillaLabel)
                            .addComponent(pastillasLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aceiteReset, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aceiteLabel)
                            .addComponent(rotAceiteLabel))
                        .addGap(15, 15, 15)))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(revisionReset)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(revisionLabel)
                            .addComponent(rotRevisionLabel))
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pastillasLabel)
                    .addComponent(aceiteLabel)
                    .addComponent(revisionLabel))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotPastillaLabel)
                    .addComponent(rotAceiteLabel)
                    .addComponent(rotRevisionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pastillasReset)
                    .addComponent(aceiteReset)
                    .addComponent(revisionReset))
                .addGap(34, 34, 34))
        );
    }// </editor-fold>                        


    private void pastillasResetActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(s.getObjetivo().getEstado() == EstadoMotor.APAGADO && s.getObjetivo().getVelocidad() == 0){
            s.getObjetivo().reiniciarPastilla();
        }
    }                                        
    private void aceiteResetActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(s.getObjetivo().getEstado() == EstadoMotor.APAGADO && s.getObjetivo().getVelocidad() == 0){
            s.getObjetivo().reiniciarAceite();
        }
    }  
    private void revisionResetActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(s.getObjetivo().getEstado() == EstadoMotor.APAGADO && s.getObjetivo().getVelocidad() == 0){
            s.getObjetivo().reiniciarRevision();
        }
    }   
    public void revisarAceite(){
        if(s.getObjetivo().getRotAceite() >= s.getObjetivo().getRotAceiteAviso()){
            aceiteLabel.setForeground(Color.red);
        }
        else
            aceiteLabel.setForeground(Color.black);
    }

    public void revisarPastillas(){
        if(s.getObjetivo().getRotPastilla() >= s.getObjetivo().getRotPastillaAviso()){
            pastillasLabel.setForeground(Color.red);
        }
        else
            pastillasLabel.setForeground(Color.black);
    } 
    public void revisarRevision(){
        if(s.getObjetivo().getRotRevision() >=  s.getObjetivo().getRotRevisionAviso()){
            revisionLabel.setForeground(Color.red);
        }
        else
        revisionLabel.setForeground(Color.black);
    }  


    public void updateInfo(){
        rotPastillaLabel.setText(String.format("%.0f", s.getObjetivo().getRotPastilla()));
        rotAceiteLabel.setText(String.format("%.0f", s.getObjetivo().getRotAceite()));
        rotRevisionLabel.setText(String.format("%.0f", s.getObjetivo().getRotRevision()));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton pastillasReset;
    private javax.swing.JButton aceiteReset;
    private javax.swing.JButton revisionReset;
    private javax.swing.JLabel rotPastillaLabel;
    private javax.swing.JLabel pastillasLabel;
    private javax.swing.JLabel aceiteLabel;
    private javax.swing.JLabel revisionLabel;
    private javax.swing.JLabel rotAceiteLabel;
    private javax.swing.JLabel rotRevisionLabel;
    // End of variables declaration            
}
