
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sergi
 */
public class tiempoSatelital extends javax.swing.JFrame implements Observer {
    public Temperatura _granada;
    public Temperatura _lugo;
    public Temperatura _madrid;
    public Temperatura _barcelona;

    /**
     * Creates new form tiempoSatelital
     */
    public tiempoSatelital(ArrayList<Temperatura> temps) {
        initComponents();
        setVisible(true);
        _granada = temps.get(0);
        _lugo = temps.get(1);
        _madrid = temps.get(2);
        _barcelona = temps.get(3);
        tempgranada.setText("-");
        templugo.setText("-");
        tempbarcelona.setText("-");
        tempmadrid.setText("-");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempgranada = new javax.swing.JLabel();
        tempmadrid = new javax.swing.JLabel();
        templugo = new javax.swing.JLabel();
        tempbarcelona = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tempgranada, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));
        getContentPane().add(tempmadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));
        getContentPane().add(templugo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));
        getContentPane().add(tempbarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mapa.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel tempbarcelona;
    private javax.swing.JLabel tempgranada;
    private javax.swing.JLabel templugo;
    private javax.swing.JLabel tempmadrid;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        tempgranada.setText(""+Math.round(_granada.getTemp()*10d)/10d+"ºC");
        templugo.setText(""+Math.round(_lugo.getTemp()*10d)/10d+"ºC");
        tempbarcelona.setText(""+Math.round(_barcelona.getTemp()*10d)/10d+"ºC");
        tempmadrid.setText(""+Math.round(_madrid.getTemp()*10d)/10d+"ºC");

    }
}
