package Vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author andres
 */
public class CuentaKilometros extends javax.swing.JPanel {
    private Salpicadero salpicadero;
    
     public CuentaKilometros(Salpicadero s) {
         salpicadero=s;
         initComponents();
     }
     
     public void actualizarCuentaKilometros(){
         contadorReciente.setText(String.format("%.2f", salpicadero.getObjetivo().getDistancia()));
         contadorTotal.setText(String.format("%.2f", salpicadero.getObjetivo().getDistanciaAbs()));      
     }
 
     /**
      * This method is called from within the constructor to initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is always
      * regenerated by the Form Editor.
      */
    
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

        contadorReciente = new javax.swing.JLabel();
        contadorTotal = new javax.swing.JLabel();
        botonReset = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("CuentaKilometros"));

        contadorReciente.setText("jLabel1");
        contadorReciente.setBorder(javax.swing.BorderFactory.createTitledBorder("Contador reciente"));

        contadorTotal.setText("jLabel2");
        contadorTotal.setBorder(javax.swing.BorderFactory.createTitledBorder("Contador total"));

        botonReset.setText("Reset");
        botonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
            .addComponent(contadorTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
            .addComponent(contadorReciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contadorReciente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(contadorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
     

     //Boton reset del cuentakilometros para poner a 0 la distancia cuando se pulse
     private void botonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResetActionPerformed
         salpicadero.getObjetivo().resetDistancia();
     }//GEN-LAST:event_botonResetActionPerformed
 
 
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton botonReset;
     private javax.swing.JLabel contadorReciente;
     private javax.swing.JLabel contadorTotal;
     // End of variables declaration//GEN-END:variables
 }
